package KieRule;
import com.sharansh.domain.Order;



rule "HDFC"

    when
        orderObject : Order(cardType=="HDFC" && price>10000);
    then
        orderObject.setDiscount(10);
end;

rule "ICICI"

    when
        orderObject : Order(cardType=="CITI" && price>15000);
    then
        orderObject.setDiscount(8);
end;

rule "DBS"

    when
        orderObject : Order(cardType=="DBS" && price>15000);
    then
        orderObject.setDiscount(15);
end;